void CGsetup(int *pjob,        
                int *pn_global,      
                int *firstrow,      
                int *lastrow,       
                int *pp,             
                int *pnnz_local,     
                int *rowptr_local,  
                int *colind_global, 
                double *values,        
                int *plocal_rank,    
                double *b_local);
