void fivept(int meshpoints , 
            int nrows    , 
            int ncols    , 
            int firstrow , 
            int lastrow  , 
            int *pnnz      , 
            int *rows     , 
            int *cols     , 
            double *vals ,
            double *rhs) ;
